version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: okto-db
    environment:
      POSTGRES_DB: t_okto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  okto-app:
#    # Ajuste o build/contexto de acordo com seu Dockerfile
#    build:
#      context: .
#      dockerfile: src/main/docker/Dockerfile.jvm
#    image: okto-app:latest
#    container_name: okto-app
#    environment:
#      # Quarkus Datasource Config via env vars
#      QUARKUS_DATASOURCE_DB_KIND: postgresql
#      QUARKUS_DATASOURCE_USERNAME: root
#      QUARKUS_DATASOURCE_PASSWORD: test
#      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/t_okto
#      QUARKUS_DATASOURCE_JDBC_MAX_SIZE: '16'
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    # Aumente a saúde da aplicação (opcional)
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
#      interval: 30s
#      timeout: 5s
#      retries: 5

volumes:
  postgres_data:
